image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - deploy

deploy_dev:
  stage: deploy
  image: "ruby:2.5"
  only:
    refs:
      - develop
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOP --api-key=$HEROKU_API_KEY
  environment:
    name: develop
    url: https://$HEROKU_APP_NAME.herokuapp.com


